title: Sydney Yan
email: syyan@stanford.edu
description: >- 
  Engineer, Scientist, Violinist, and Puzzler

baseurl: "" 
url: "https://sydneyyan.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag